### ISSUE TITLE
Theme makes pop-up menus unreadable

### ISSUE THREAD

**Issue by mattringel** [jstnjns/min-ui#1]
Using Atom on Windows 10.  This theme makes pop-up menus such as the command pallette and the new folder form unreadable with a red background.  I tried it with various syntax themes and they all have the same problem.

![image](https://cloud.githubusercontent.com/assets/18271252/14367152/51e3c2f8-fccb-11e5-9dc5-dd9b7db7233b.png)

**Comment by MutableLoss** [comment]
Yes, same issue with Linux Ubuntu 15.04, and OSX El Capitan. 

First off, I want to say this theme is great!  

It seems that the only issue is in the inactive dropdown fonts. A unsaturated gray on top of a highly saturated red blends right in:

![command](https://cloud.githubusercontent.com/assets/3156278/15807893/6d528128-2b2e-11e6-831c-4f8f0ec7b2b4.jpg)

You can see this same behavior when using a dropdown menu where the bg is white, but the font is still that same light gray:. 

![font](https://cloud.githubusercontent.com/assets/3156278/15807894/719f199e-2b2e-11e6-9b35-65a04f636463.jpg)

I'm not an Atom theme creator, so I have no idea if this font is somewhere else. A low value colored font should fix these areas, but I'm guessing they could be used somewhere else where it would break things (Command palette hotkey background?). 

Thanks, and hope to see an update soon! So nice to have a dark minimal theme. :)

**Comment by ghost** [comment]
same on mac, @sdomula's PR fixes it

<img width="300" alt="min-ui-fixed-overlay" src="https://cloud.githubusercontent.com/assets/1907029/22375980/4416ec44-e47a-11e6-9f1c-a8266c9848de.png">
